# array

In [39]:
import numpy as np

In [46]:
test_array = np.array([2,3,4],float)

In [43]:
print(test_array)
type(test_array[2]) # Float Type으로 자동 형변환
print(test_array.dtype) # Array 전체의 데이터 type 반환
print(test_array.shape) # Array의 shape 반환

[2. 3. 4.]
float64
(3,)


 ### array(vector, matrix, tensor)의 크기 형태

In [21]:
tensor = [[1,2],[1,2]]
print(np.array(tensor, int).ndim) #number of dimension
print(np.array(tensor, int).size) #data의 개수

2
4


### dtype
#### Ndarray의 요소들이 가지는 data type & memory 크기 결정됨

In [28]:
print(np.array([[1,2,3],[7,8,9]], dtype= int))
print(np.array([[1,2,3],[7,8,9.5]], dtype=np.float32))

[[1 2 3]
 [7 8 9]]
[[1.  2.  3. ]
 [7.  8.  9.5]]


## Basic type-------Available NumPy types
### Boolean-----------------------------------bool
###   integar-----------------------int 8, 16, 32, 64, 128, int
### Unsigned integer ---------uint 8, 16, 32, 64, 128, uint
### Float--------------------------float 32, 64, float, longfloat
### Complex----------------------complex64, 128, complex
### Strings--------------------------------str, unicode
### Object------------------------------------object
### Record-------------------------------------void

# Reshape
### arrya의 shape의 크기를 변경함(element 개수 동일)

In [50]:
test_matrix = [[1,2,3,4], [2,3,4,6]]
np.array(test_matrix).shape

(2, 4)

In [51]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 2, 3, 4, 6])

In [52]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [54]:
np.array(test_matrix).reshape(-1,2) # -1 : size를 기반으로 row 개수 설정

array([[1, 2],
       [3, 4],
       [2, 3],
       [4, 6]])

In [55]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[2, 3],
        [4, 6]]])

In [58]:
np.array(test_matrix).reshape(4,-1,2)

array([[[1, 2]],

       [[3, 4]],

       [[2, 3]],

       [[4, 6]]])

# flatten
## 다차원 array를 1차원 array로 변환

In [59]:
test_matrix = [[1,2,3,4], [2,3,4,6]]

In [61]:
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 2, 3, 4, 6])

# indexing
## list와 달리 이차원 배열에서 [0, 0]과 같은 표기법 제공
## matrix일경우 앞은 row, 뒤는 column

In [68]:
a = np.array([[1,2,3],[3,4,5]], int)

In [69]:
print(a)

[[1 2 3]
 [3 4 5]]


In [70]:
print(a[0,0]) # 2차원
print(a[0][0])

1
1


In [71]:
a[0,0] = 12
print(a)

[[12  2  3]
 [ 3  4  5]]


# slicing
## list와 달리 행과 열 부분을 나눠서 slicing이 가능함
## matrix의 부분 집합을 추출할 때 유용함

In [81]:
a = np.array([[1,2,3,6,7],[4,5,3,4,5]], int)

In [82]:
a[:,1:] #  row 3열 이상

array([[2, 3, 6, 7],
       [5, 3, 4, 5]])

In [83]:
a[1,1:3] 

array([5, 3])

In [84]:
a[:,:]

array([[1, 2, 3, 6, 7],
       [4, 5, 3, 4, 5]])

In [85]:
a[:,::2] #step 2만큼

array([[1, 3, 7],
       [4, 3, 5]])

# arange
## array의 범위를 지정, 값의 list를 생성하는 명령어

In [88]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [89]:
np.arange(0,5,0.5) # 시작, 끝, step

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [90]:
np.arange(30).reshape(3,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

# ones, zeros and empty
## zeros -0으로 가득찬 ndarray

In [99]:
np.zeros(shape=(10,2), dtype = np.int8)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

In [100]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## ones - 1로 가득찬 ndarray

In [101]:
np.ones(shape=(10,), dtype = np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [102]:
np.ones((2,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

## empty - shape만 주어지고 비어있는 ndarray (memory initialization 되지 않음)

In [103]:
np.empty(shape = (10,), dtype = np.int8)

array([  96,  -99,  -99, -103,   16,    1,    0,    0,    0,    0],
      dtype=int8)

In [104]:
np.empty((4,5))

array([[2.37663529e-312, 2.14321575e-312, 2.37663529e-312,
        2.56761491e-312, 2.44029516e-312],
       [2.05833592e-312, 2.14321575e-312, 1.29441743e-312,
        8.48798317e-313, 1.01855798e-312],
       [8.70018275e-313, 6.79038653e-313, 2.46151512e-312,
        2.37663529e-312, 6.79038654e-313],
       [6.79038653e-313, 2.37663529e-312, 2.22809558e-312,
        2.46151512e-312, 8.70018275e-313]])

# someting like
## 기존 ndarray의 shape 크기 만큼 1, 0 또는 empty array 반환

In [106]:
test_matrix = np.arange(30).reshape(3,10)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

# identity
## 단위 행렬 (i 행렬)을 생성함
## n -> number of rows

In [115]:
np.identity(n=3, dtype = np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [116]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# eye
## 대각선이 1인 행렬
## k값의 시작 index의 변경이 가능
## k -> index start

In [119]:
np.eye(N=3, M=5, dtype = np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [120]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [121]:
np.eye(3,6,k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

# diag
## 대각 행렬의 값 추출
## k -> index start

In [124]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [125]:
np.diag(matrix)

array([0, 4, 8])

In [126]:
np.diag(matrix, k = 2)

array([2])

# random sampling
## 데이터 분포에 따른 sampling 으로 array 생성

In [127]:
np.random.uniform(0,1,10).reshape(2,5) # 균등분포 - >  최저값, 최고값, 데이터값

array([[0.11420829, 0.70218605, 0.06987966, 0.42235403, 0.9865    ],
       [0.33068861, 0.93720235, 0.58363694, 0.92430582, 0.01927368]])

In [128]:
np.random.normal(0,1,10).reshape(2,5) # 정규분포

array([[ 0.98447054, -1.02344855,  0.01454409,  2.77754633, -1.88415068],
       [ 0.04686583,  0.5030364 , -0.35074582, -0.0299274 , -0.38383918]])

# sum
## ndarray의 element들 간의 합을 구함
## list의 sum 동일

In [130]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
np.sum(test_array)

55

In [133]:
test_array.sum(dtype = np.float)

55.0

# axis
## 모든 operation function을 실행할 때, 기준이 되는 dimension 축

In [134]:
test_array = np.arange(1,15).reshape(2,7)
test_array

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [139]:
test_array.sum(axis = 1), test_array.sum(axis=0)

(array([28, 77]), array([ 9, 11, 13, 15, 17, 19, 21]))

In [149]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14]]])

In [150]:
third_order_tensor.sum(axis = 0)

array([[ 3,  6],
       [ 9, 12],
       [15, 18],
       [21, 24],
       [27, 30],
       [33, 36],
       [39, 42]])

In [151]:
third_order_tensor.sum(axis = 1)

array([[49, 56],
       [49, 56],
       [49, 56]])

In [152]:
third_order_tensor.sum(axis = 2)

array([[ 3,  7, 11, 15, 19, 23, 27],
       [ 3,  7, 11, 15, 19, 23, 27],
       [ 3,  7, 11, 15, 19, 23, 27]])

# mean & std
## ndarry의 element들 간의 평균 또는 표준 편차 반환

In [153]:
test_array = np.arange(1,15).reshape(7,2)
test_array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [154]:
test_array.mean(), test_array.mean(axis = 0)

(7.5, array([7., 8.]))

In [155]:
test_array.std(), test_array.std(axis = 1)

(4.031128874149275, array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]))

# concatenate
## numpy array를 합치는 함수

In [156]:
a = np.array([2,3,4])
b = np.array([5,6,8])
np.vstack((a,b)) # 수직으로 더해줌

array([[2, 3, 4],
       [5, 6, 8]])

In [158]:
a = np.array([[3],[4],[5]])
b = np.array([[8],[6],[2]])
np.hstack((a,b)) #수평으로 더해줌

array([[3, 8],
       [4, 6],
       [5, 2]])

In [161]:
a = np.array([[2,3,4]])
b = np.array([[5,6,8]])
np.concatenate((a,b), axis = 0)

array([[2, 3, 4],
       [5, 6, 8]])

In [162]:
a = np.array([[3],[4],[5]])
b = np.array([[8],[6],[2]])
np.concatenate((a,b), axis = 1)

array([[3, 8],
       [4, 6],
       [5, 2]])

In [164]:
a = np.array([[1,2],[3,4]])
b = np.array([[6,8]])
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 6],
       [3, 4, 8]])

# operation b/t arrays
## numpy는 array 간의 기본적인 사칙 연산 지원

In [166]:
test_a = np.array([[1,5,6],[7,8,9]],float)

In [168]:
test_a + test_a

array([[ 2., 10., 12.],
       [14., 16., 18.]])

In [170]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [171]:
test_a * test_a # matrix내 element들 간 같은 위치에 있는 값들끼리 연산

array([[ 1., 25., 36.],
       [49., 64., 81.]])

# element-wise operation
## array 간 shape이 같을 때 일어나는 연산

In [174]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

# Dot product
## matrix의 기본 연산
## dot 함수 사용

In [181]:
test_a = np.arange(1,16).reshape(3,5)
test_b = np.arange(1,16).reshape(3,5)

In [182]:
print(test_a)
print(test_b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [183]:
test_a.dot(test_b.T)

array([[ 55, 130, 205],
       [130, 330, 530],
       [205, 530, 855]])

# Transpose
## transpose 또는 T attribute 사용

In [184]:
test_a = np.arange(1,9).reshape(2,4)
test_a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [187]:
test_a.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [188]:
test_a.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [186]:
test_a.dot(test_a.T)

array([[ 30,  70],
       [ 70, 174]])

# broadcasting
## shape이 다른 배열 간 연산을 자동으로! 지원하는 기능

In [194]:
test_matrix = np.arange(1,11).reshape(2,5)
test_matrix
scalar = 3

In [195]:
test_matrix + scalar # scalar 값 각각 더해준다

array([[ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13]])

In [196]:
test_matrix - scalar

array([[-2, -1,  0,  1,  2],
       [ 3,  4,  5,  6,  7]])

In [197]:
test_matrix * scalar

array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30]])

In [198]:
test_matrix / scalar

array([[0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667],
       [2.        , 2.33333333, 2.66666667, 3.        , 3.33333333]])

In [199]:
test_matrix // scalar

array([[0, 0, 1, 1, 1],
       [2, 2, 2, 3, 3]], dtype=int32)

In [200]:
test_matrix ** scalar

array([[   1,    8,   27,   64,  125],
       [ 216,  343,  512,  729, 1000]], dtype=int32)

In [206]:
test_matrix = np.arange(1,25).reshape(4,6)
test_vector = np.arange(5,25,5).reshape(4,-1)
test_matrix + test_vector

array([[ 6,  7,  8,  9, 10, 11],
       [17, 18, 19, 20, 21, 22],
       [28, 29, 30, 31, 32, 33],
       [39, 40, 41, 42, 43, 44]])

# numpy performance #!
## timeit : jupyter 환경에서 코드의 퍼포먼스를 체크하는 함수

In [208]:
def sclar_vector_product(scalar, vector) :
    result = []
    for value in vector :
        result.append(scalar * value)
    return result

iternation_max = 100000000

vector = list(range(iternation_max))
scalar = 2

In [209]:
vector

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [ ]:
%timeit sclar_vector_product(scalar, vector) # for loop을 이용한 성능

In [ ]:
%timeit [scalar * value for value in range(iternation max)] #list comprehension을 이용한 성능

In [ ]:
%timeit np.arange(iternation_max) * scalar # numpy 이용한 성능

# All & Any
## array 의 데이터 전부 (and) 또는 일부(or) 가 조건에 만족 여부 반환
## any -> 하나라도 조건에 만족한다면 true
## all -> 모두가 조건에 만족한다면 true

In [212]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [213]:
np.any(a>5), np.all(a<0)

(True, False)

In [214]:
np.any(a>5), np.all(a >= 0)

(True, True)

# comparison operation #1
## numpy는 배열의 크기가 동일 할 때
## element간 비교의 결과를 boolean type으로 반환하여 돌려줌

In [216]:
test_a = np.array([2,5,6],float)
test_b = np.array([5,7,8],float)
test_a > test_b

array([False, False, False])

In [217]:
test_a == test_b

array([False, False, False])

In [218]:
(test_a > test_b).any()

False

# comparison opertaion #2

In [243]:
a = np.array([2,6,7],float)
np.logical_and(a > 0, a < 3) # and 조건의 condition

array([ True, False, False])

In [244]:
b = np.array([True,False,True], bool)
np.logical_not(b) # not 조건의 condition

array([False,  True, False])

In [245]:
c = np.array([False, True, False], bool)
np.logical_or(b,c) # or 조건의 condition

array([ True,  True,  True])

In [246]:
np.where( a > 0, 3, 2)

array([3, 3, 3])

# np.where
## where (condition, TRUE, FALSE)

In [251]:
a = np.arange(10)
np.where(a>5,3,2) # index 값 반환

array([2, 2, 2, 2, 2, 2, 3, 3, 3, 3])

In [252]:
a > 10

array([False, False, False, False, False, False, False, False, False,
       False])

In [255]:
a = np.array([99, np.NaN, np.Inf], float)
np.isnan(a) # not a number 

array([False,  True, False])

In [256]:
np.isfinite(a) # is finite number

array([ True, False, False])

# argmax & argmin
## array 내 최대값 또는 최소값의 index 반환
## axis 기준으로 반환 가능

In [265]:
a = np.array([[1,2,3,4,7,8,9],[3,4,5,6,1,2,4]])
a

array([[1, 2, 3, 4, 7, 8, 9],
       [3, 4, 5, 6, 1, 2, 4]])

In [266]:
np.argmax(a), np.argmin(a)

(6, 0)

In [267]:
np.argmax(a, axis = 0), np.argmin(a, axis = 1)

(array([1, 1, 1, 1, 0, 0, 0], dtype=int64), array([0, 4], dtype=int64))

# boolean index
## numpy는 배열은 특정 조건에 따른 값을 배열 형태로 추출 할 수 있음
## comparison operation 함수들도 모두 사용가능

In [269]:
test_array = np.array([2,4,6,7,8,0],float)
test_array > 3

array([False,  True,  True,  True,  True, False])

In [270]:
test_array[test_array > 3] # 조건이 true인 index의 element만 추출

array([4., 6., 7., 8.])

In [273]:
condition = test_array < 3 
test_array[condition]

array([2., 0.])

In [275]:
a = np.arange(1,16).reshape(5,-1)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [277]:
b = a < 9
b.astype(np.int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

# fancy index
## numpy는 array 를 index value로 사용해서 값을 추출하는 방법
## matrix 형태의 데이터도 가능

In [282]:
a = np.array([2,3,5,6], float)
b = np.array([0,1,2,3,3,2], int) # 반드시 integar로 선언
a[b] #bracket index, b 배열의 값을 index로 하여 a 값들을 추출

array([2., 3., 5., 6., 6., 5.])

In [283]:
a.take(b) #take 함수 : bracket index 와 같은 효과

array([2., 3., 5., 6., 6., 5.])

In [291]:
a = np.array([[2,6,7,3],[1,8,9,3]], float)
b = np.array([0,1,0,1,1,1], int)
c = np.array([0,2,3,1,1,1], int)
a[b,c] # b를 row index, c를 column index로 변환하여 표시

array([2., 9., 3., 8., 8., 8.])

 # loadtxt & savetxt
 ## text type의 데이터를 읽고, 저장하는 기능

In [ ]:
a = np.loadtext("./populations.txt") #파일 호출
a[:10]

In [ ]:
a_int = a.astype(int) # int type 변환
a_int[:3]

In [ ]:
np.savetxt("int_data.csv", a_int, delimiter = ",") #int_data.csv로 저장

# numpy object - npy
## numpy object (pickle) 형태로 데이터를 저장하고 불러옴
## binary 파일 형태로 저장함

In [ ]:
np.save("npy_test", arr = a_int)

In [ ]:
npy_array = np.load(file = "npy_test.npy")

In [ ]:
npy_array